server:
  port: '8089'
spring:
  application:
    name: trip-division-service
  config:
    import: configserver:http://localhost:8086
  datasource:    
    url: jdbc:mysql://localhost:3306/tripdivisionservice
    password: Welcome@1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
